### PR TITLE
AVX-21740: Allow interface to be set for SNAT and DNAT policies with …

### LINKED ISSUE #1253: SNAT rules not created
**Describe the problem**

resource "aviatrix_gateway_snat" "gateway_snat_test" {
    gw_name = "vpn-01"
    snat_mode = "customized_snat"
    snat_policy {
        src_cidr = "x.x.x.x/32"
        dst_cidr = "x.x.x.x/24"
        protocol = "all"
        interface = "eth0"
        connection = "VPN@site2cloud"
        snat_ips = "x.x.x.x"
    }
    sync_to_ha = false
}

if  interface = "eth0" is put in the code the error is : Error: failed to create policies for 'cutomised_snat' mode: 'interface' must be empty when 'connection' is set
if the interface = "" the error is : error : "[AVXERR-NAT-0043] Failed to get interface for connection [VPN@site2cloud]."

policy based tunnel !

**To Reproduce**

policy based tunnel !

**Expected behaviour**
SNAT rules should have been created 

**Environment:**
 - aviatrix 2.21.2
 - Terraform v1.1.7
 - Aviatrix Controller UserConnect-6.6.5545

### PR DESCRIPTION
**Pull request by mlin-aviatrix**
…policy-based connections

### CODE REVIEW

File: aviatrix/utils.go [hunk 1]
```diff
@@ -216,6 +216,18 @@ func DiffSuppressFuncGCPVpcId(k, old, new string, d *schema.ResourceData) bool {
...
 }
 
+func DiffSuppressFuncNatInterface(k, old, new string, d *schema.ResourceData) bool {
+	connectionKey := strings.Replace(k, "interface", "connection", 1)
+	connection := d.Get(connectionKey).(string)
+	// Must check if ID != "" so that interface can be set on initial create. Without
+	// this check, the value for interface will be suppressed and interface = "" will
+	// be passed to the API even if interface = "eth0" in the configuration.
+	if d.Id() != "" && !(connection == "" || connection == "None") {
+		return old == "" && new == "eth0"
```
Comment (mlin-aviatrix) [inline aviatrix/utils.go:226]: The main cases to consider for this are the following

1. Policy-based connection - old should never be empty so this should not effect it
2. Route-based connection - old will always be empty so this will suppress a diff when new == "eth0"
3. No connection - No changes

**Review by zhiqiangjin — APPROVED** [review]

**Review by shuoliugit — APPROVED** [review]
